"""update event table

Revision ID: 088dba899e6d
Revises: 5c45025fe182
Create Date: 2026-04-09 22:50:28.165944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '088dba899e6d'
down_revision: Union[str, Sequence[str], None] = '5c45025fe182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('ended_at', sa.DateTime(), nullable=False))
    op.drop_column('event', 'end_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('event', 'ended_at')
    # ### end Alembic commands ###
